name: Deploy-Dev
on:
  push:
    branches:
      - develop
#  pull_request:
#    branches:
#      - develop
#    types: [closed]
jobs:
  inject-source:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: Develop
    steps:
      - name: execute commands via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_MACHINE }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWD }}
          port: ${{ secrets.PORT }}
          script: systemctl stop coc-web.service                ;
            cd /srv                                             &&
            rm -rf fe-web                                       &&
            git clone https://github.com/coclabs/fe-web.git     &&
            cd fe-web                                           &&
            git checkout develop                                &&
            git pull                                            &&
            yarn install                                        &&
            systemctl start coc-web.service
      - name: notify discord
      uses: sarisia/actions-status-discord@v1.8.5
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: Deploy dev fe-web
        description: Development codebase deploy via ssh source injection
        username: GitHub Actions
